{{
FluentForm::withAction(action('Auth\AuthController@postRegister'))
->withValues(old())
->withErrors($errors)
->withLabels(trans('validation.attributes'))
->withToken(csrf_token())
->containingInputBlock('workplace.name')->required()
->followedByInputBlock('workplace.employees','number')->withInputAttribute(['min'=>1, 'max'=>65535])->required()
->followedByInputBlock('workplace.occupations')->withInputAttribute('data-occupationsurl', action('OccupationController@index'))->withDescription(trans('workplace.occupations.description'))
->followedByInputBlock('workplace.address','textarea')->required()
->followedByInputBlock('workplace.description','textarea')->required()->withDescription(trans('workplace.description.description'))
->followedByInputBlock('user.name')->required()->withDescription(trans('workplace.contact.description'))
->followedByInputBlock('user.email','email')->required()
->followedByInputBlock('user.phone','tel')->required()
->followedByPasswordBlock('user.password')->withLabel(trans('auth.labels.desired_password'))->required()
->followedByPasswordBlock('user.password_confirmation')->withLabel(trans('auth.labels.password_confirmation'))->required()
->followedByButtonBlock(trans('auth.actions.register_workplace'))
}}